#!/bin/sh
SH_FILE=`readlink -f $0`
SH_DIR=`dirname ${SH_FILE}`

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:STAGING_LIBDIR_NATIVE/classpath:STAGING_LIBDIR_NATIVE/jamvm"
export BOOTCLASSPATH="STAGING_DATADIR_NATIVE/jamvm/classes.zip:STAGING_DATADIR_NATIVE/classpath/glibj.zip"
exec ${SH_DIR}/jamvm "$@"
